/*
export interface BlanksContent {
    media: Media;
    text: string;
    overallFeedback: OverallFeedback[];
    showSolutions: string;
    tryAgain: string;
    checkAnswer: string;
    submitAnswer: string;
    notFilledOut: string;
    answerIsCorrect: string;
    answerIsWrong: string;
    answeredCorrectly: string;
    answeredIncorrectly: string;
    solutionLabel: string;
    inputLabel: string;
    inputHasTipLabel: string;
    tipLabel: string;
    behaviour: BehaviourConfig;
    scoreBarLabel: string;
    a11yCheck: string;
    a11yShowSolution: string;
    a11yRetry: string;
    a11yCheckingModeHeader: string;
    confirmCheck: Confirm;
    confirmRetry: Confirm;
    questions: string[];
}

export interface BehaviourConfig {
    enableRetry: boolean;
    allowRetryIfCorrect: boolean;
    enableSolutionsButton: boolean;
    enableCheckButton: boolean;
    autoCheck: boolean;
    caseSensitive: boolean;
    showSolutionsRequiresInput: boolean;
    separateLines: boolean;
    confirmCheckDialog: boolean;
    confirmRetryDialog: boolean;
    acceptSpellingErrors: boolean;
}

export interface Confirm {
    header: string;
    body: string;
    cancelLabel: string;
    confirmLabel: string;
}

export interface Media {
    disableImageZooming: boolean;
}

export interface OverallFeedback {
    from: number;
    to: number;
}
*/
// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";

export const mediaSchema = z.object({
    disableImageZooming: z.boolean()
});

export const overallFeedbackSchema = z.object({
    from: z.number(),
    to: z.number()
});

export const behaviourConfigSchema = z.object({
    enableRetry: z.boolean(),
    allowRetryIfCorrect: z.boolean(),
    enableSolutionsButton: z.boolean(),
    enableCheckButton: z.boolean(),
    autoCheck: z.boolean(),
    caseSensitive: z.boolean(),
    showSolutionsRequiresInput: z.boolean(),
    separateLines: z.boolean(),
    confirmCheckDialog: z.boolean(),
    confirmRetryDialog: z.boolean(),
    acceptSpellingErrors: z.boolean()
});

export const confirmSchema = z.object({
    header: z.string(),
    body: z.string(),
    cancelLabel: z.string(),
    confirmLabel: z.string()
});

export const blanksContentSchema = z.object({
    media: mediaSchema,
    text: z.string(),
    overallFeedback: z.array(overallFeedbackSchema),
    showSolutions: z.string(),
    tryAgain: z.string(),
    checkAnswer: z.string(),
    submitAnswer: z.string(),
    notFilledOut: z.string(),
    answerIsCorrect: z.string(),
    answerIsWrong: z.string(),
    answeredCorrectly: z.string(),
    answeredIncorrectly: z.string(),
    solutionLabel: z.string(),
    inputLabel: z.string(),
    inputHasTipLabel: z.string(),
    tipLabel: z.string(),
    behaviour: behaviourConfigSchema,
    scoreBarLabel: z.string(),
    a11yCheck: z.string(),
    a11yShowSolution: z.string(),
    a11yRetry: z.string(),
    a11yCheckingModeHeader: z.string(),
    confirmCheck: confirmSchema,
    confirmRetry: confirmSchema,
    questions: z.array(z.string())
});

// inferred types:
export type Media = z.infer<typeof mediaSchema>;

export type OverallFeedback = z.infer<typeof overallFeedbackSchema>;

export type BehaviourConfig = z.infer<typeof behaviourConfigSchema>;

export type Confirm = z.infer<typeof confirmSchema>;

export type BlanksContent = z.infer<typeof blanksContentSchema>;