/*
export interface DialogcardsContent {
    mode: string;
    dialogs: Dialog[];
    behaviour: Behaviour;
    answer: string;
    next: string;
    prev: string;
    retry: string;
    correctAnswer: string;
    incorrectAnswer: string;
    round: string;
    cardsLeft: string;
    nextRound: string;
    startOver: string;
    showSummary: string;
    summary: string;
    summaryCardsRight: string;
    summaryCardsWrong: string;
    summaryCardsNotShown: string;
    summaryOverallScore: string;
    summaryCardsCompleted: string;
    summaryCompletedRounds: string;
    summaryAllDone: string;
    progressText: string;
    cardFrontLabel: string;
    cardBackLabel: string;
    tipButtonLabel: string;
    audioNotSupported: string;
    confirmStartingOver: ConfirmStartingOver;
    title: string;
    description: string;
}

export interface Behaviour {
    enableRetry: boolean;
    disableBackwardsNavigation: boolean;
    scaleTextNotCard: boolean;
    randomCards: boolean;
    maxProficiency: number;
    quickProgression: boolean;
}

export interface ConfirmStartingOver {
    header: string;
    body: string;
    cancelLabel: string;
    confirmLabel: string;
}

export interface Dialog {
    text: string;
    answer: string;
    tips: Record<string, unknown>;
    audio?: AudioItem[] 
}

// export interface Tips {
// }
export interface Copyright {
    license: string;
}
export interface AudioItem {
    path: string;
    mime: string;
    copyright?: Copyright;
}
*/
// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";

export const behaviourSchema = z.object({
    enableRetry: z.boolean(),
    disableBackwardsNavigation: z.boolean(),
    scaleTextNotCard: z.boolean(),
    randomCards: z.boolean(),
    maxProficiency: z.number(),
    quickProgression: z.boolean()
});

export const confirmStartingOverSchema = z.object({
    header: z.string(),
    body: z.string(),
    cancelLabel: z.string(),
    confirmLabel: z.string()
});

// export interface Tips {
// }
export const copyrightSchema = z.object({
    license: z.string()
});

export const audioItemSchema = z.object({
    path: z.string(),
    mime: z.string(),
    copyright: copyrightSchema.optional()
});

export const dialogSchema = z.object({
    text: z.string(),
    answer: z.string(),
    tips: z.object({}),
    audio: z.array(audioItemSchema).optional()
});

export const dialogcardsContentSchema = z.object({
    mode: z.string(),
    dialogs: z.array(dialogSchema),
    behaviour: behaviourSchema,
    answer: z.string(),
    next: z.string(),
    prev: z.string(),
    retry: z.string(),
    correctAnswer: z.string(),
    incorrectAnswer: z.string(),
    round: z.string(),
    cardsLeft: z.string(),
    nextRound: z.string(),
    startOver: z.string(),
    showSummary: z.string(),
    summary: z.string(),
    summaryCardsRight: z.string(),
    summaryCardsWrong: z.string(),
    summaryCardsNotShown: z.string(),
    summaryOverallScore: z.string(),
    summaryCardsCompleted: z.string(),
    summaryCompletedRounds: z.string(),
    summaryAllDone: z.string(),
    progressText: z.string(),
    cardFrontLabel: z.string(),
    cardBackLabel: z.string(),
    tipButtonLabel: z.string(),
    audioNotSupported: z.string(),
    confirmStartingOver: confirmStartingOverSchema,
    title: z.string(),
    description: z.string()
});

// inferred types:
export type Behaviour = z.infer<typeof behaviourSchema>;

export type ConfirmStartingOver = z.infer<typeof confirmStartingOverSchema>;

export type Copyright = z.infer<typeof copyrightSchema>;

export type AudioItem = z.infer<typeof audioItemSchema>;

export type Dialog = z.infer<typeof dialogSchema>;

export type DialogcardsContent = z.infer<typeof dialogcardsContentSchema>;