/*
export interface DragTextContent {
    media:                Media;
    taskDescription:      string;
    overallFeedback:      OverallFeedback[];
    checkAnswer:          string;
    submitAnswer:         string;
    tryAgain:             string;
    showSolution:         string;
    dropZoneIndex:        string;
    empty:                string;
    contains:             string;
    ariaDraggableIndex:   string;
    tipLabel:             string;
    correctText:          string;
    incorrectText:        string;
    resetDropTitle:       string;
    resetDropDescription: string;
    grabbed:              string;
    cancelledDragging:    string;
    correctAnswer:        string;
    feedbackHeader:       string;
    behaviour:            Behaviour;
    scoreBarLabel:        string;
    a11yCheck:            string;
    a11yShowSolution:     string;
    a11yRetry:            string;
    textField:            string;
    distractors:          string;
}

export interface Behaviour {
    enableRetry:           boolean;
    enableSolutionsButton: boolean;
    enableCheckButton:     boolean;
    instantFeedback:       boolean;
}

export interface Media {
    disableImageZooming: boolean;
}

export interface OverallFeedback {
    from: number;
    to:   number;
}
*/
////////////
// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";

export const mediaSchema = z.object({
    disableImageZooming: z.boolean()
});

export const overallFeedbackSchema = z.object({
    from: z.number(),
    to: z.number()
});

export const behaviourSchema = z.object({
    enableRetry: z.boolean(),
    enableSolutionsButton: z.boolean(),
    enableCheckButton: z.boolean(),
    instantFeedback: z.boolean()
});

export const dragTextContentSchema = z.object({
    media: mediaSchema,
    taskDescription: z.string(),
    overallFeedback: z.array(overallFeedbackSchema),
    checkAnswer: z.string(),
    submitAnswer: z.string(),
    tryAgain: z.string(),
    showSolution: z.string(),
    dropZoneIndex: z.string(),
    empty: z.string(),
    contains: z.string(),
    ariaDraggableIndex: z.string(),
    tipLabel: z.string(),
    correctText: z.string(),
    incorrectText: z.string(),
    resetDropTitle: z.string(),
    resetDropDescription: z.string(),
    grabbed: z.string(),
    cancelledDragging: z.string(),
    correctAnswer: z.string(),
    feedbackHeader: z.string(),
    behaviour: behaviourSchema,
    scoreBarLabel: z.string(),
    a11yCheck: z.string(),
    a11yShowSolution: z.string(),
    a11yRetry: z.string(),
    textField: z.string(),
    distractors: z.string()
});

// inferred types:
export type Media = z.infer<typeof mediaSchema>;

export type OverallFeedback = z.infer<typeof overallFeedbackSchema>;

export type Behaviour = z.infer<typeof behaviourSchema>;

export type DragTextContent = z.infer<typeof dragTextContentSchema>;