/*
export interface MultimediaChoiceContent {
    media:           MultimediaChoiceContentMedia;
    options:         Option[];
    overallFeedback: OverallFeedback[];
    behaviour:       Behaviour;
    l10n:            L10N;
    question:        string;
}

export interface Behaviour {
    enableRetry:                boolean;
    enableSolutionsButton:      boolean;
    confirmCheckDialog:         boolean;
    confirmRetryDialog:         boolean;
    singlePoint:                boolean;
    showSolutionsRequiresInput: boolean;
    questionType:               string;
    aspectRatio:                string;
    maxAlternativesPerRow:      string;
    passPercentage:             number;
}

export interface L10N {
    checkAnswerButtonText:  string;
    submitAnswerButtonText: string;
    checkAnswer:            string;
    showSolutionButtonText: string;
    showSolution:           string;
    correctAnswer:          string;
    wrongAnswer:            string;
    shouldCheck:            string;
    shouldNotCheck:         string;
    noAnswer:               string;
    retryText:              string;
    retry:                  string;
    result:                 string;
    missingAltText:         string;
    closeModalText:         string;
    confirmCheck:           Confirm;
    confirmRetry:           Confirm;
}

export interface Confirm {
    header:       string;
    body:         string;
    cancelLabel:  string;
    confirmLabel: string;
}

export interface MultimediaChoiceContentMedia {
    disableImageZooming: boolean;
}

export interface Option {
    media:   OptionMedia;
    correct: boolean;
    poster:  Poster;
}

export interface OptionMedia {
    params:       Params;
    library:      string;
    metadata:     Metadata;
    subContentId: string;
}

export interface Metadata {
    contentType: string;
    license:     string;
    title:       string;
}

export interface Params {
    playerMode:        string;
    fitToWrapper:      boolean;
    controls:          boolean;
    autoplay:          boolean;
    playAudio:         string;
    pauseAudio:        string;
    contentName:       string;
    audioNotSupported: string;
    files:             File[];
}

export interface File {
    path:      string;
    mime:      string;
    copyright: Copyright;
}

export interface Copyright {
    license: string;
}

export interface Poster {
    path:      string;
    mime:      string;
    copyright: Copyright;
    width:     number;
    height:    number;
}

export interface OverallFeedback {
    from: number;
    to:   number;
}
*/
// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";

export const multimediaChoiceContentMediaSchema = z.object({
    disableImageZooming: z.boolean()
});

export const overallFeedbackSchema = z.object({
    from: z.number(),
    to: z.number()
});

export const behaviourSchema = z.object({
    enableRetry: z.boolean(),
    enableSolutionsButton: z.boolean(),
    confirmCheckDialog: z.boolean(),
    confirmRetryDialog: z.boolean(),
    singlePoint: z.boolean(),
    showSolutionsRequiresInput: z.boolean(),
    questionType: z.string(),
    aspectRatio: z.string(),
    maxAlternativesPerRow: z.string(),
    passPercentage: z.number()
});

export const confirmSchema = z.object({
    header: z.string(),
    body: z.string(),
    cancelLabel: z.string(),
    confirmLabel: z.string()
});

export const metadataSchema = z.object({
    contentType: z.string(),
    license: z.string(),
    title: z.string()
});

export const copyrightSchema = z.object({
    license: z.string()
});

export const l10nSchema = z.object({
    checkAnswerButtonText: z.string(),
    submitAnswerButtonText: z.string(),
    checkAnswer: z.string(),
    showSolutionButtonText: z.string(),
    showSolution: z.string(),
    correctAnswer: z.string(),
    wrongAnswer: z.string(),
    shouldCheck: z.string(),
    shouldNotCheck: z.string(),
    noAnswer: z.string(),
    retryText: z.string(),
    retry: z.string(),
    result: z.string(),
    missingAltText: z.string(),
    closeModalText: z.string(),
    confirmCheck: confirmSchema,
    confirmRetry: confirmSchema
});

export const posterSchema = z.object({
    path: z.string(),
    mime: z.string(),
    copyright: copyrightSchema,
    width: z.number(),
    height: z.number()
});

export const fileSchema = z.object({
    path: z.string(),
    mime: z.string(),
    copyright: copyrightSchema
});

export const paramsSchema = z.object({
    playerMode: z.string(),
    fitToWrapper: z.boolean(),
    controls: z.boolean(),
    autoplay: z.boolean(),
    playAudio: z.string(),
    pauseAudio: z.string(),
    contentName: z.string(),
    audioNotSupported: z.string(),
    files: z.array(fileSchema)
});

export const optionMediaSchema = z.object({
    params: paramsSchema,
    library: z.string(),
    metadata: metadataSchema,
    subContentId: z.string()
});

export const optionSchema = z.object({
    media: optionMediaSchema,
    correct: z.boolean(),
    poster: posterSchema
});

export const multimediaChoiceContentSchema = z.object({
    media: multimediaChoiceContentMediaSchema,
    options: z.array(optionSchema),
    overallFeedback: z.array(overallFeedbackSchema),
    behaviour: behaviourSchema,
    l10n: l10nSchema,
    question: z.string()
});

// inferred types:
export type MultimediaChoiceContentMedia = z.infer<typeof multimediaChoiceContentMediaSchema>;

export type OverallFeedback = z.infer<typeof overallFeedbackSchema>;

export type Behaviour = z.infer<typeof behaviourSchema>;

export type Confirm = z.infer<typeof confirmSchema>;

export type Metadata = z.infer<typeof metadataSchema>;

export type Copyright = z.infer<typeof copyrightSchema>;

export type L10N = z.infer<typeof l10nSchema>;

export type Poster = z.infer<typeof posterSchema>;

export type File = z.infer<typeof fileSchema>;

export type Params = z.infer<typeof paramsSchema>;

export type OptionMedia = z.infer<typeof optionMediaSchema>;

export type Option = z.infer<typeof optionSchema>;

export type MultimediaChoiceContent = z.infer<typeof multimediaChoiceContentSchema>;