/*
export interface MultiChoiceContent {
    media:           Media;
    answers:         Answer[];
    overallFeedback: OverallFeedback[];
    behaviour:       Behaviour;
    UI:              UI;
    confirmCheck:    Confirm;
    confirmRetry:    Confirm;
    question:        string;
}

export interface UI {
    checkAnswerButton:  string;
    submitAnswerButton: string;
    showSolutionButton: string;
    tryAgainButton:     string;
    tipsLabel:          string;
    scoreBarLabel:      string;
    tipAvailable:       string;
    feedbackAvailable:  string;
    readFeedback:       string;
    wrongAnswer:        string;
    correctAnswer:      string;
    shouldCheck:        string;
    shouldNotCheck:     string;
    noInput:            string;
    a11yCheck:          string;
    a11yShowSolution:   string;
    a11yRetry:          string;
}

export interface Answer {
    correct:         boolean;
    tipsAndFeedback: TipsAndFeedback;
    text:            string;
}

export interface TipsAndFeedback {
    tip:               string;
    chosenFeedback:    string;
    notChosenFeedback: string;
}

export interface Behaviour {
    enableRetry:                boolean;
    enableSolutionsButton:      boolean;
    enableCheckButton:          boolean;
    type:                       string;
    singlePoint:                boolean;
    randomAnswers:              boolean;
    showSolutionsRequiresInput: boolean;
    confirmCheckDialog:         boolean;
    confirmRetryDialog:         boolean;
    autoCheck:                  boolean;
    passPercentage:             number;
    showScorePoints:            boolean;
}

export interface Confirm {
    header:       string;
    body:         string;
    cancelLabel:  string;
    confirmLabel: string;
}

export interface Media {
    disableImageZooming: boolean;
    type:                Type;
}

export interface Type {
    params:       Params;
    library:      string;
    metadata:     Metadata;
    subContentId: string;
}

export interface Metadata {
    contentType: string;
    license:     string;
    title:       string;
}

export interface Params {
    playerMode:        string;
    fitToWrapper:      boolean;
    controls:          boolean;
    autoplay:          boolean;
    playAudio:         string;
    pauseAudio:        string;
    contentName:       string;
    audioNotSupported: string;
    files:             File[];
}

export interface File {
    path:      string;
    mime:      string;
    copyright: Copyright;
}

export interface Copyright {
    license: string;
}

export interface OverallFeedback {
    from: number;
    to:   number;
}
export interface MultiChoiceContent {
    media:           Media;
    answers:         Answer[];
    overallFeedback: OverallFeedback[];
    behaviour:       Behaviour;
    UI:              UI;
    confirmCheck:    Confirm;
    confirmRetry:    Confirm;
    question:        string;
}

export interface UI {
    checkAnswerButton:  string;
    submitAnswerButton: string;
    showSolutionButton: string;
    tryAgainButton:     string;
    tipsLabel:          string;
    scoreBarLabel:      string;
    tipAvailable:       string;
    feedbackAvailable:  string;
    readFeedback:       string;
    wrongAnswer:        string;
    correctAnswer:      string;
    shouldCheck:        string;
    shouldNotCheck:     string;
    noInput:            string;
    a11yCheck:          string;
    a11yShowSolution:   string;
    a11yRetry:          string;
}

export interface Answer {
    correct:         boolean;
    tipsAndFeedback: TipsAndFeedback;
    text:            string;
}

export interface TipsAndFeedback {
    tip:               string;
    chosenFeedback:    string;
    notChosenFeedback: string;
}

export interface Behaviour {
    enableRetry:                boolean;
    enableSolutionsButton:      boolean;
    enableCheckButton:          boolean;
    type:                       string;
    singlePoint:                boolean;
    randomAnswers:              boolean;
    showSolutionsRequiresInput: boolean;
    confirmCheckDialog:         boolean;
    confirmRetryDialog:         boolean;
    autoCheck:                  boolean;
    passPercentage:             number;
    showScorePoints:            boolean;
}

export interface Confirm {
    header:       string;
    body:         string;
    cancelLabel:  string;
    confirmLabel: string;
}

export interface Media {
    disableImageZooming: boolean;
}

export interface OverallFeedback {
    from: number;
    to:   number;
}
*/
// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";

export const mediaSchema = z.object({
    disableImageZooming: z.boolean()
});

export const overallFeedbackSchema = z.object({
    from: z.number(),
    to: z.number()
});

export const behaviourSchema = z.object({
    enableRetry: z.boolean(),
    enableSolutionsButton: z.boolean(),
    enableCheckButton: z.boolean(),
    type: z.string(),
    singlePoint: z.boolean(),
    randomAnswers: z.boolean(),
    showSolutionsRequiresInput: z.boolean(),
    confirmCheckDialog: z.boolean(),
    confirmRetryDialog: z.boolean(),
    autoCheck: z.boolean(),
    passPercentage: z.number(),
    showScorePoints: z.boolean()
});

export const uiSchema = z.object({
    checkAnswerButton: z.string(),
    submitAnswerButton: z.string(),
    showSolutionButton: z.string(),
    tryAgainButton: z.string(),
    tipsLabel: z.string(),
    scoreBarLabel: z.string(),
    tipAvailable: z.string(),
    feedbackAvailable: z.string(),
    readFeedback: z.string(),
    wrongAnswer: z.string(),
    correctAnswer: z.string(),
    shouldCheck: z.string(),
    shouldNotCheck: z.string(),
    noInput: z.string(),
    a11yCheck: z.string(),
    a11yShowSolution: z.string(),
    a11yRetry: z.string()
});

export const confirmSchema = z.object({
    header: z.string(),
    body: z.string(),
    cancelLabel: z.string(),
    confirmLabel: z.string()
});

export const tipsAndFeedbackSchema = z.object({
    tip: z.string(),
    chosenFeedback: z.string(),
    notChosenFeedback: z.string()
});

export const metadataSchema = z.object({
    contentType: z.string(),
    license: z.string(),
    title: z.string()
});

export const copyrightSchema = z.object({
    license: z.string()
});

export const answerSchema = z.object({
    correct: z.boolean(),
    tipsAndFeedback: tipsAndFeedbackSchema,
    text: z.string()
});

export const fileSchema = z.object({
    path: z.string(),
    mime: z.string(),
    copyright: copyrightSchema
});

export const multiChoiceContentSchema = z.object({
    media: mediaSchema,
    answers: z.array(answerSchema),
    overallFeedback: z.array(overallFeedbackSchema),
    behaviour: behaviourSchema,
    UI: uiSchema,
    confirmCheck: confirmSchema,
    confirmRetry: confirmSchema,
    question: z.string()
});

export const paramsSchema = z.object({
    playerMode: z.string(),
    fitToWrapper: z.boolean(),
    controls: z.boolean(),
    autoplay: z.boolean(),
    playAudio: z.string(),
    pauseAudio: z.string(),
    contentName: z.string(),
    audioNotSupported: z.string(),
    files: z.array(fileSchema)
});

export const typeSchema = z.object({
    params: paramsSchema,
    library: z.string(),
    metadata: metadataSchema,
    subContentId: z.string()
});

// inferred types:
export type Media = z.infer<typeof mediaSchema>;

export type OverallFeedback = z.infer<typeof overallFeedbackSchema>;

export type Behaviour = z.infer<typeof behaviourSchema>;

export type UI = z.infer<typeof uiSchema>;

export type Confirm = z.infer<typeof confirmSchema>;

export type TipsAndFeedback = z.infer<typeof tipsAndFeedbackSchema>;

export type Metadata = z.infer<typeof metadataSchema>;

export type Copyright = z.infer<typeof copyrightSchema>;

export type Answer = z.infer<typeof answerSchema>;

export type File = z.infer<typeof fileSchema>;

export type MultiChoiceContent = z.infer<typeof multiChoiceContentSchema>;

export type Params = z.infer<typeof paramsSchema>;

export type Type = z.infer<typeof typeSchema>;