/*
export interface QuestionSetContent {
    introPage: IntroPage;
    progressType: string;
    passPercentage: number;
    questions: Question[];
    disableBackwardsNavigation: boolean;
    randomQuestions: boolean;
    endGame: EndGame;
    override: Override;
    texts: Texts;
}

export interface EndGame {
    showResultPage: boolean;
    showSolutionButton: boolean;
    showRetryButton: boolean;
    noResultMessage: string;
    message: string;
    amountCorrect: string;
    scoreBarLabel: string;
    scoreHeader: string;
    overallFeedback: OverallFeedback[];
    solutionButtonText: string;
    retryButtonText: string;
    finishButtonText: string;
    submitButtonText: string;
    showAnimations: boolean;
    skippable: boolean;
    skipButtonText: string;
}

export interface OverallFeedback {
    from: number;
    to: number;
}

export interface IntroPage {
    showIntroPage: boolean;
    startButtonText: string;
    introduction: string;
}

export interface Override {
    checkButton: boolean;
}

export interface Question {
    params: Params;
    library: string;
    metadata: Metadata;
    subContentId: string;
}

export interface Metadata {
    contentType: string;
    license: string;
    title: string;
}

export interface Params {
    media: Media;
    answers: Answer[];
    overallFeedback: OverallFeedback[];
    behaviour: Behaviour;
    UI: UI;
    confirmCheck: Confirm;
    confirmRetry: Confirm;
    question: string;
}

export interface UI {
    checkAnswerButton: string;
    submitAnswerButton: string;
    showSolutionButton: string;
    tryAgainButton: string;
    tipsLabel: string;
    scoreBarLabel: string;
    tipAvailable: string;
    feedbackAvailable: string;
    readFeedback: string;
    wrongAnswer: string;
    correctAnswer: string;
    shouldCheck: string;
    shouldNotCheck: string;
    noInput: string;
    a11yCheck: string;
    a11yShowSolution: string;
    a11yRetry: string;
}

export interface Answer {
    correct: boolean;
    tipsAndFeedback: TipsAndFeedback;
    text: string;
}

export interface TipsAndFeedback {
    tip: string;
    chosenFeedback: string;
    notChosenFeedback: string;
}

export interface Behaviour {
    enableRetry: boolean;
    enableSolutionsButton: boolean;
    enableCheckButton: boolean;
    type: string;
    singlePoint: boolean;
    randomAnswers: boolean;
    showSolutionsRequiresInput: boolean;
    confirmCheckDialog: boolean;
    confirmRetryDialog: boolean;
    autoCheck: boolean;
    passPercentage: number;
    showScorePoints: boolean;
}

export interface Confirm {
    header: string;
    body: string;
    cancelLabel: string;
    confirmLabel: string;
}

export interface Media {
    disableImageZooming: boolean;
}

export interface Texts {
    prevButton: string;
    previous: string;
    nextButton: string;
    next: string;
    finishButton: string;
    submitButton: string;
    textualProgress: string;
    jumpToQuestion: string;
    questionLabel: string;
    readSpeakerProgress: string;
    unansweredText: string;
    answeredText: string;
    currentQuestionText: string;
    navigationLabel: string;
    questionSetInstruction: string;
}
*/
// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";

export const introPageSchema = z.object({
    showIntroPage: z.boolean(),
    startButtonText: z.string(),
    introduction: z.string()
});

export const overrideSchema = z.object({
    checkButton: z.boolean()
});

export const textsSchema = z.object({
    prevButton: z.string(),
    previous: z.string(),
    nextButton: z.string(),
    next: z.string(),
    finishButton: z.string(),
    submitButton: z.string(),
    textualProgress: z.string(),
    jumpToQuestion: z.string(),
    questionLabel: z.string(),
    readSpeakerProgress: z.string(),
    unansweredText: z.string(),
    answeredText: z.string(),
    currentQuestionText: z.string(),
    navigationLabel: z.string(),
    questionSetInstruction: z.string()
});

export const overallFeedbackSchema = z.object({
    from: z.number(),
    to: z.number()
});

export const metadataSchema = z.object({
    contentType: z.string(),
    license: z.string(),
    title: z.string()
});

export const mediaSchema = z.object({
    disableImageZooming: z.boolean()
});

export const behaviourSchema = z.object({
    enableRetry: z.boolean(),
    enableSolutionsButton: z.boolean(),
    enableCheckButton: z.boolean(),
    type: z.string(),
    singlePoint: z.boolean(),
    randomAnswers: z.boolean(),
    showSolutionsRequiresInput: z.boolean(),
    confirmCheckDialog: z.boolean(),
    confirmRetryDialog: z.boolean(),
    autoCheck: z.boolean(),
    passPercentage: z.number(),
    showScorePoints: z.boolean()
});

export const uiSchema = z.object({
    checkAnswerButton: z.string(),
    submitAnswerButton: z.string(),
    showSolutionButton: z.string(),
    tryAgainButton: z.string(),
    tipsLabel: z.string(),
    scoreBarLabel: z.string(),
    tipAvailable: z.string(),
    feedbackAvailable: z.string(),
    readFeedback: z.string(),
    wrongAnswer: z.string(),
    correctAnswer: z.string(),
    shouldCheck: z.string(),
    shouldNotCheck: z.string(),
    noInput: z.string(),
    a11yCheck: z.string(),
    a11yShowSolution: z.string(),
    a11yRetry: z.string()
});

export const confirmSchema = z.object({
    header: z.string(),
    body: z.string(),
    cancelLabel: z.string(),
    confirmLabel: z.string()
});

export const tipsAndFeedbackSchema = z.object({
    tip: z.string(),
    chosenFeedback: z.string(),
    notChosenFeedback: z.string()
});

export const endGameSchema = z.object({
    showResultPage: z.boolean(),
    showSolutionButton: z.boolean(),
    showRetryButton: z.boolean(),
    noResultMessage: z.string(),
    message: z.string(),
    amountCorrect: z.string(),
    scoreBarLabel: z.string(),
    scoreHeader: z.string(),
    overallFeedback: z.array(overallFeedbackSchema),
    solutionButtonText: z.string(),
    retryButtonText: z.string(),
    finishButtonText: z.string(),
    submitButtonText: z.string(),
    showAnimations: z.boolean(),
    skippable: z.boolean(),
    skipButtonText: z.string()
});

export const answerSchema = z.object({
    correct: z.boolean(),
    tipsAndFeedback: tipsAndFeedbackSchema,
    text: z.string()
});

export const paramsSchema = z.object({
    media: mediaSchema,
    answers: z.array(answerSchema),
    overallFeedback: z.array(overallFeedbackSchema),
    behaviour: behaviourSchema,
    UI: uiSchema,
    confirmCheck: confirmSchema,
    confirmRetry: confirmSchema,
    question: z.string()
});

export const questionSchema = z.object({
    params: paramsSchema,
    library: z.string(),
    metadata: metadataSchema,
    subContentId: z.string()
});

export const questionSetContentSchema = z.object({
    introPage: introPageSchema,
    progressType: z.string(),
    passPercentage: z.number(),
    questions: z.array(questionSchema),
    disableBackwardsNavigation: z.boolean(),
    randomQuestions: z.boolean(),
    endGame: endGameSchema,
    override: overrideSchema,
    texts: textsSchema
});

// inferred types:
export type IntroPage = z.infer<typeof introPageSchema>;

export type Override = z.infer<typeof overrideSchema>;

export type Texts = z.infer<typeof textsSchema>;

export type OverallFeedback = z.infer<typeof overallFeedbackSchema>;

export type Metadata = z.infer<typeof metadataSchema>;

export type Media = z.infer<typeof mediaSchema>;

export type Behaviour = z.infer<typeof behaviourSchema>;

export type UI = z.infer<typeof uiSchema>;

export type Confirm = z.infer<typeof confirmSchema>;

export type TipsAndFeedback = z.infer<typeof tipsAndFeedbackSchema>;

export type EndGame = z.infer<typeof endGameSchema>;

export type Answer = z.infer<typeof answerSchema>;

export type Params = z.infer<typeof paramsSchema>;

export type Question = z.infer<typeof questionSchema>;

export type QuestionSetContent = z.infer<typeof questionSetContentSchema>;