/////////////////////////////////
/*
export interface SingleChoiceSetContent {
    choices: Choice[];
    overallFeedback: OverallFeedback[];
    behaviour: Behaviour;
    l10n: L10N;
}

export interface Behaviour {
    autoContinue: boolean;
    timeoutCorrect: number;
    timeoutWrong: number;
    soundEffectsEnabled: boolean;
    enableRetry: boolean;
    enableSolutionsButton: boolean;
    passPercentage: number;
}

export interface Choice {
    subContentId: string;
    question: string;
    answers: string[];
}

export interface L10N {
    nextButtonLabel: string;
    nextButton: string;
    showResultsButtonLabel: string;
    retryButtonLabel: string;
    solutionViewTitle: string;
    correctText: string;
    incorrectText: string;
    shouldSelect: string;
    shouldNotSelect: string;
    muteButtonLabel: string;
    closeButtonLabel: string;
    slideOfTotal: string;
    scoreBarLabel: string;
    solutionListQuestionNumber: string;
    a11yShowSolution: string;
    a11yRetry: string;
    resultHeader: string;
    totalScore: string;
    resultTableHeader: string;
    resultScoreTableHeader: string;
    correctAnswerIntroduction: string;
}

export interface OverallFeedback {
    from: number;
    to: number;
}
*/
// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";

export const choiceSchema = z.object({
    subContentId: z.string(),
    question: z.string(),
    answers: z.array(z.string())
});

export const overallFeedbackSchema = z.object({
    from: z.number(),
    to: z.number()
});

export const behaviourSchema = z.object({
    autoContinue: z.boolean(),
    timeoutCorrect: z.number(),
    timeoutWrong: z.number(),
    soundEffectsEnabled: z.boolean(),
    enableRetry: z.boolean(),
    enableSolutionsButton: z.boolean(),
    passPercentage: z.number()
});

export const l10nSchema = z.object({
    nextButtonLabel: z.string(),
    nextButton: z.string(),
    showResultsButtonLabel: z.string(),
    retryButtonLabel: z.string(),
    solutionViewTitle: z.string(),
    correctText: z.string(),
    incorrectText: z.string(),
    shouldSelect: z.string(),
    shouldNotSelect: z.string(),
    muteButtonLabel: z.string(),
    closeButtonLabel: z.string(),
    slideOfTotal: z.string(),
    scoreBarLabel: z.string(),
    solutionListQuestionNumber: z.string(),
    a11yShowSolution: z.string(),
    a11yRetry: z.string(),
    resultHeader: z.string(),
    totalScore: z.string(),
    resultTableHeader: z.string(),
    resultScoreTableHeader: z.string(),
    correctAnswerIntroduction: z.string()
});

/////////////////////////////////
export const singleChoiceSetContentSchema = z.object({
    choices: z.array(choiceSchema),
    overallFeedback: z.array(overallFeedbackSchema),
    behaviour: behaviourSchema,
    l10n: l10nSchema
});

// inferred types:
export type Choice = z.infer<typeof choiceSchema>;

export type OverallFeedback = z.infer<typeof overallFeedbackSchema>;

export type Behaviour = z.infer<typeof behaviourSchema>;

export type L10N = z.infer<typeof l10nSchema>;

export type SingleChoiceSetContent = z.infer<typeof singleChoiceSetContentSchema>;