// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
//Some schemas can't be generated due to direct or indirect missing dependencies:
//blanksActionSchema
//dialogCardsActionSchema
//singleChoiceSetActionSchema
//multiChoiceActionSchema
//multiMediaChoiceActionSchema
//dragTextActionSchema
//actionSchema
//elementSchema
//slideSchema
//presentationSchema
//coursePresentationContentSchema

import { z } from "zod";
import { License } from "";

export const facebookShareSchema = z.object({
    url: z.string(),
    quote: z.string()
});

export const twitterShareSchema = z.object({
    statement: z.string(),
    url: z.string(),
    hashtags: z.string()
});

export const globalBackgroundSelectorSchema = z.object({});

export const licenseSchema = z.nativeEnum(License);

export const behaviourSchema = z.object({
    enableRetry: z.boolean(),
    disableBackwardsNavigation: z.boolean().optional(),
    scaleTextNotCard: z.boolean().optional(),
    randomCards: z.boolean().optional(),
    maxProficiency: z.number().optional(),
    quickProgression: z.boolean().optional(),
    autoContinue: z.boolean().optional(),
    timeoutCorrect: z.number().optional(),
    timeoutWrong: z.number().optional(),
    soundEffectsEnabled: z.boolean().optional(),
    enableSolutionsButton: z.boolean().optional(),
    passPercentage: z.number().optional(),
    enableCheckButton: z.boolean().optional(),
    type: z.string().optional(),
    singlePoint: z.boolean().optional(),
    randomAnswers: z.boolean().optional(),
    showSolutionsRequiresInput: z.boolean().optional(),
    confirmCheckDialog: z.boolean().optional(),
    confirmRetryDialog: z.boolean().optional(),
    autoCheck: z.boolean().optional(),
    showScorePoints: z.boolean().optional(),
    allowRetryIfCorrect: z.boolean().optional(),
    caseSensitive: z.boolean().optional(),
    separateLines: z.boolean().optional(),
    acceptSpellingErrors: z.boolean().optional(),
    aspectRatio: z.string().optional(),
    questionType: z.string().optional(),
    maxAlternativesPerRow: z.string().optional(),
    instantFeedback: z.boolean().optional()
});

export const confirmSchema = z.object({
    header: z.string(),
    body: z.string(),
    cancelLabel: z.string(),
    confirmLabel: z.string()
});

export const choiceSchema = z.object({
    subContentId: z.string(),
    question: z.string().optional(),
    answers: z.array(z.string()).optional()
});

export const overallFeedbackSchema = z.object({
    from: z.number(),
    to: z.number()
});

export const l10nSchema = z.object({
    nextButtonLabel: z.string().optional(),
    nextButton: z.string().optional(),
    showResultsButtonLabel: z.string().optional(),
    retryButtonLabel: z.string().optional(),
    solutionViewTitle: z.string().optional(),
    correctText: z.string().optional(),
    incorrectText: z.string().optional(),
    shouldSelect: z.string().optional(),
    shouldNotSelect: z.string().optional(),
    muteButtonLabel: z.string().optional(),
    closeButtonLabel: z.string().optional(),
    slideOfTotal: z.string().optional(),
    scoreBarLabel: z.string().optional(),
    solutionListQuestionNumber: z.string().optional(),
    a11yShowSolution: z.string().optional(),
    a11yRetry: z.string().optional(),
    resultHeader: z.string().optional(),
    totalScore: z.string().optional(),
    resultTableHeader: z.string().optional(),
    resultScoreTableHeader: z.string().optional(),
    correctAnswerIntroduction: z.string().optional(),
    checkAnswerButtonText: z.string().optional(),
    submitAnswerButtonText: z.string().optional(),
    checkAnswer: z.string().optional(),
    showSolutionButtonText: z.string().optional(),
    showSolution: z.string().optional(),
    correctAnswer: z.string().optional(),
    wrongAnswer: z.string().optional(),
    shouldCheck: z.string().optional(),
    shouldNotCheck: z.string().optional(),
    noAnswer: z.string().optional(),
    retryText: z.string().optional(),
    retry: z.string().optional(),
    result: z.string().optional(),
    missingAltText: z.string().optional(),
    closeModalText: z.string().optional(),
    confirmCheck: confirmSchema.optional(),
    confirmRetry: confirmSchema.optional()
});

export const uiSchema = z.object({
    checkAnswerButton: z.string(),
    submitAnswerButton: z.string(),
    showSolutionButton: z.string(),
    tryAgainButton: z.string(),
    tipsLabel: z.string(),
    scoreBarLabel: z.string(),
    tipAvailable: z.string(),
    feedbackAvailable: z.string(),
    readFeedback: z.string(),
    wrongAnswer: z.string(),
    correctAnswer: z.string(),
    shouldCheck: z.string(),
    shouldNotCheck: z.string(),
    noInput: z.string(),
    a11yCheck: z.string(),
    a11yShowSolution: z.string(),
    a11yRetry: z.string()
});

export const tipsAndFeedbackSchema = z.object({
    tip: z.string(),
    chosenFeedback: z.string(),
    notChosenFeedback: z.string()
});

export const copyrightSchema = z.object({
    license: licenseSchema
});

export const socialSchema = z.object({
    showFacebookShare: z.boolean(),
    facebookShare: facebookShareSchema,
    showTwitterShare: z.boolean(),
    twitterShare: twitterShareSchema,
    showGoogleShare: z.boolean(),
    googleShareUrl: z.string()
});

export const metadataSchema = z.object({
    contentType: z.string(),
    license: licenseSchema,
    title: z.string()
});

export const answerSchema = z.object({
    correct: z.boolean(),
    tipsAndFeedback: tipsAndFeedbackSchema,
    text: z.string()
});

export const audioSchema = z.object({
    path: z.string(),
    mime: z.string(),
    copyright: copyrightSchema
});

export const typeParamsSchema = z.object({
    playerMode: z.string(),
    fitToWrapper: z.boolean(),
    controls: z.boolean(),
    autoplay: z.boolean(),
    playAudio: z.string(),
    pauseAudio: z.string(),
    contentName: z.string(),
    audioNotSupported: z.string(),
    files: z.array(audioSchema)
});

export const overrideSchema = z.object({
    activeSurface: z.boolean(),
    hideSummarySlide: z.boolean(),
    summarySlideSolutionButton: z.boolean(),
    summarySlideRetryButton: z.boolean(),
    enablePrintButton: z.boolean(),
    social: socialSchema
});

const baseActionSchema = z.object({
    subContentId: z.string(),
    metadata: metadataSchema
});

export const dialogSchema = z.object({
    text: z.string(),
    answer: z.string(),
    tips: globalBackgroundSelectorSchema,
    audio: z.array(audioSchema)
});

export const typeSchema = z.object({
    params: typeParamsSchema,
    library: z.string(),
    metadata: metadataSchema,
    subContentId: z.string()
});

export const mediaSchema = z.object({
    disableImageZooming: z.boolean(),
    type: typeSchema.optional()
});

export const optionSchema = z.object({
    media: typeSchema,
    correct: z.boolean()
});

export const actionParamsSchema = z.object({
    mode: z.string().optional(),
    dialogs: z.array(dialogSchema).optional(),
    behaviour: behaviourSchema,
    answer: z.string().optional(),
    next: z.string().optional(),
    prev: z.string().optional(),
    retry: z.string().optional(),
    correctAnswer: z.string().optional(),
    incorrectAnswer: z.string().optional(),
    round: z.string().optional(),
    cardsLeft: z.string().optional(),
    nextRound: z.string().optional(),
    startOver: z.string().optional(),
    showSummary: z.string().optional(),
    summary: z.string().optional(),
    summaryCardsRight: z.string().optional(),
    summaryCardsWrong: z.string().optional(),
    summaryCardsNotShown: z.string().optional(),
    summaryOverallScore: z.string().optional(),
    summaryCardsCompleted: z.string().optional(),
    summaryCompletedRounds: z.string().optional(),
    summaryAllDone: z.string().optional(),
    progressText: z.string().optional(),
    cardFrontLabel: z.string().optional(),
    cardBackLabel: z.string().optional(),
    tipButtonLabel: z.string().optional(),
    audioNotSupported: z.string().optional(),
    confirmStartingOver: confirmSchema.optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    choices: z.array(choiceSchema).optional(),
    overallFeedback: z.array(overallFeedbackSchema).optional(),
    l10n: l10nSchema.optional(),
    media: mediaSchema.optional(),
    answers: z.array(answerSchema).optional(),
    UI: uiSchema.optional(),
    confirmCheck: confirmSchema.optional(),
    confirmRetry: confirmSchema.optional(),
    question: z.string().optional(),
    text: z.string().optional(),
    showSolutions: z.string().optional(),
    tryAgain: z.string().optional(),
    checkAnswer: z.string().optional(),
    submitAnswer: z.string().optional(),
    notFilledOut: z.string().optional(),
    answerIsCorrect: z.string().optional(),
    answerIsWrong: z.string().optional(),
    answeredCorrectly: z.string().optional(),
    answeredIncorrectly: z.string().optional(),
    solutionLabel: z.string().optional(),
    inputLabel: z.string().optional(),
    inputHasTipLabel: z.string().optional(),
    tipLabel: z.string().optional(),
    scoreBarLabel: z.string().optional(),
    a11yCheck: z.string().optional(),
    a11yShowSolution: z.string().optional(),
    a11yRetry: z.string().optional(),
    a11yCheckingModeHeader: z.string().optional(),
    questions: z.array(z.string()).optional(),
    options: z.array(optionSchema).optional(),
    taskDescription: z.string().optional(),
    showSolution: z.string().optional(),
    dropZoneIndex: z.string().optional(),
    empty: z.string().optional(),
    contains: z.string().optional(),
    ariaDraggableIndex: z.string().optional(),
    correctText: z.string().optional(),
    incorrectText: z.string().optional(),
    resetDropTitle: z.string().optional(),
    resetDropDescription: z.string().optional(),
    grabbed: z.string().optional(),
    cancelledDragging: z.string().optional(),
    feedbackHeader: z.string().optional(),
    textField: z.string().optional()
});
// 2. Define the Base Action fields
// 3. Create the Action Discriminated Union
export const actionSchema = z.discriminatedUnion("library", [
  baseActionSchema.extend({
    library: z.literal("H5P.Blanks"),
    params: blanksContentSchema,
  }),
  baseActionSchema.extend({
    library: z.literal("H5P.Dialogcards"),
    params: dialogcardsContentSchema,
  }),
  // Add your other actions here following the exact same pattern:
  // baseActionSchema.extend({ library: z.literal("H5P.MultiChoice"), params: multiChoiceSchema })
]);
// inferred types:
export type FacebookShare = z.infer<typeof facebookShareSchema>;

export type TwitterShare = z.infer<typeof twitterShareSchema>;

export type GlobalBackgroundSelector = z.infer<typeof globalBackgroundSelectorSchema>;

export type License = z.infer<typeof licenseSchema>;

export type Behaviour = z.infer<typeof behaviourSchema>;

export type Confirm = z.infer<typeof confirmSchema>;

export type Choice = z.infer<typeof choiceSchema>;

export type OverallFeedback = z.infer<typeof overallFeedbackSchema>;

export type L10N = z.infer<typeof l10nSchema>;

export type UI = z.infer<typeof uiSchema>;

export type TipsAndFeedback = z.infer<typeof tipsAndFeedbackSchema>;

export type Copyright = z.infer<typeof copyrightSchema>;

export type Social = z.infer<typeof socialSchema>;

export type Metadata = z.infer<typeof metadataSchema>;

export type Answer = z.infer<typeof answerSchema>;

export type Audio = z.infer<typeof audioSchema>;

export type TypeParams = z.infer<typeof typeParamsSchema>;

export type Override = z.infer<typeof overrideSchema>;

export type Dialog = z.infer<typeof dialogSchema>;

export type Type = z.infer<typeof typeSchema>;

export type Media = z.infer<typeof mediaSchema>;

export type Option = z.infer<typeof optionSchema>;

export type ActionParams = z.infer<typeof actionParamsSchema>;