// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";

export const mediaSchema = z.object({
    disableImageZooming: z.boolean()
});

export const overallFeedbackSchema = z.object({
    from: z.number(),
    to: z.number()
});

export const behaviourConfigSchema = z.object({
    enableRetry: z.boolean(),
    allowRetryIfCorrect: z.boolean(),
    enableSolutionsButton: z.boolean(),
    enableCheckButton: z.boolean(),
    autoCheck: z.boolean(),
    caseSensitive: z.boolean(),
    showSolutionsRequiresInput: z.boolean(),
    separateLines: z.boolean(),
    confirmCheckDialog: z.boolean(),
    confirmRetryDialog: z.boolean(),
    acceptSpellingErrors: z.boolean()
});

export const confirmSchema = z.object({
    header: z.string(),
    body: z.string(),
    cancelLabel: z.string(),
    confirmLabel: z.string()
});

export const blanksContentSchema = z.object({
    media: mediaSchema,
    text: z.string(),
    overallFeedback: z.array(overallFeedbackSchema),
    showSolutions: z.string(),
    tryAgain: z.string(),
    checkAnswer: z.string(),
    submitAnswer: z.string(),
    notFilledOut: z.string(),
    answerIsCorrect: z.string(),
    answerIsWrong: z.string(),
    answeredCorrectly: z.string(),
    answeredIncorrectly: z.string(),
    solutionLabel: z.string(),
    inputLabel: z.string(),
    inputHasTipLabel: z.string(),
    tipLabel: z.string(),
    behaviour: behaviourConfigSchema,
    scoreBarLabel: z.string(),
    a11yCheck: z.string(),
    a11yShowSolution: z.string(),
    a11yRetry: z.string(),
    a11yCheckingModeHeader: z.string(),
    confirmCheck: confirmSchema,
    confirmRetry: confirmSchema,
    questions: z.array(z.string())
});

// inferred types:
export type Media = z.infer<typeof mediaSchema>;

export type OverallFeedback = z.infer<typeof overallFeedbackSchema>;

export type BehaviourConfig = z.infer<typeof behaviourConfigSchema>;

export type Confirm = z.infer<typeof confirmSchema>;

export type BlanksContent = z.infer<typeof blanksContentSchema>;